### PR TITLE
Loginpage

### PR DESCRIPTION
**Pull request by Klan300**

### CODE REVIEW

**Comment by Klan300** [comment]
- [x] pull from this branch  install requirement.txt and migrate

- [ ] can login by gmail and facebook

- [ ] can log out

**Comment by EJEunjiyaz** [comment]
Great, there is no problem with this branch.

**Review by kornkritpawit — APPROVED** [review]
Have some unused line, but overall is great.

**Comment by Parkkung** [comment]
have a problem that can login only by developer account @facebooklogin

**Comment by Klan300** [comment]
x;cjvds;fgj

**Review by Parkkung — APPROVED** [review]

**Comment by Parkkung** [comment]
ok, already fix fblogin

**Pull request merged**
