### PR TITLE
Playpage

### PR DESCRIPTION
**Pull request by kornkritpawit**
I make the HTML elements to be flex and div pattern. I think it actually great. Please review my code.

### CODE REVIEW

**Comment by kornkritpawit** [comment]
Almost complete. Everyone reviews my code, please.

**Review by Klan300 — CHANGES_REQUESTED** [review]
- [x]  change color background to #536d82.

- [x] drop-down color green on the background when it correct. I think it too much bright.

- [x] please fix some bug when it out of card the game should be finish.

**Comment by Klan300** [comment]
pls change folder CardGame to Cardgame

**Comment by kornkritpawit** [comment]
fiinish changing

**Review by Klan300 — APPROVED** [review]
everything ok

**Review by Parkkung — APPROVED** [review]

**Comment by Parkkung** [comment]
Very nice play page

**Pull request merged**
